# Check `docs/pipeline.md` to get info about this file
resources:
  - name: hellokite-repository
    type: git
    source:
      uri: https://github.com/calj/hellokite.git
      branch: master

  - name: hellokite-image
    type: docker-image
    source:
      repository: gcr.io/helios-devel/hellokite
      username: _json_key
      password: ((gcr_password))


jobs:
  - name: build
    serial: true
    plan:
      - get: hellokite-repository
        trigger: true

      - task: tag
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine/git
          run:
            path: sh
            args: ['-xc', 'cd hellokite-repository && git rev-parse --short=8 HEAD > ../tag/name']
          inputs:
            - name: hellokite-repository
          outputs:
            - name: tag

      - put: hellokite-image
        params:
          build: hellokite-repository
          tag: tag/name

  - name: test
    serial: true
    plan:
      - get: hellokite-image
        passed: [build]
        trigger: true

      - get: hellokite-repository
        passed: [build]
        trigger: true

      - task: run-tests
        image: hellokite-image
        config:
          platform: linux
          run:
            path: sh
            args: ["-xc", "find / 2> /dev/null | grep server.js"]
