# Check `docs/pipeline.md` to get info about this file
resources:
  - name: hellokite-repo
    type: git
    source:
      uri: https://github.com/calj/hellokite.git
      branch: master

  - name: hellokite-image
    type: docker-image
    source:
      repository: gcr.io/helios-devel/hellokite
      username: _json_key
      password: ((gcr_password))

jobs:

  - name: build-master
    serial: true
    plan:
      - get: hellokite-repo
        trigger: true
      - put: hellokite-image
        params:
          build: hellokite-repo

  - name: shipit
    serial: true
    plan:
      - get: hellokite-repo
      - task: helm-package
        file: hellokite-repo/.kite/pipelines/tasks/helm-package.yml

      - task: helm-deploy
        params:
          GOOGLE_APPLICATION_JSON: ((gcr_key))
        config:
          platform: linux

          image_resource:
            type: docker-image
            source:
              repository: linkyard/docker-helm

          inputs:
            - name: hellokite-repo
          run:
            path: "sh"
            args:
              - "-exc"
              - |
                echo ${GOOGLE_APPLICATION_JSON} > gcr_credentials.json
                export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/gcr_credentials.json"
